// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDOkVb80WQ3OSmxi1HA5qgEjwLLktyQhJE',
    appId: '1:210411111773:android:19ebefabb057f9d7c1d4b4',
    messagingSenderId: '210411111773',
    projectId: 'beering-824d7',
    storageBucket: 'beering-824d7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDkQC5B3ckyamw2nr9M8tqxruQ7PsfbS9I',
    appId: '1:210411111773:ios:71a835ba2aefcc9ec1d4b4',
    messagingSenderId: '210411111773',
    projectId: 'beering-824d7',
    storageBucket: 'beering-824d7.appspot.com',
    androidClientId: '210411111773-mdah2ia1l1a6kdvtuniiokppgp40gp78.apps.googleusercontent.com',
    iosClientId: '210411111773-den95douqtosrj7h8u6ad5d0hrobv0sp.apps.googleusercontent.com',
    iosBundleId: 'com.bees.app',
  );
}
