name: bees4
description: A new Flutter project.
version: 1.0.0+1
environment: 
  sdk: '>=2.17.0 <3.0.0'
dependencies: 
  flutter: 
    sdk: flutter
  cached_network_image: ^3.2.1
  flutter_svg: ^1.1.6
  intl: ^0.18.0
  viam_sdk: ^0.0.9
  firebase_core: ^2.24.2
  firebase_auth: ^4.6.1
  firebase_ui_auth: ^1.4.0
  flutterfire_ui: ^0.4.3+20
  google_sign_in: ^5.4.4

dependency_overrides:
  firebase_auth: "4.12.0"
  
dev_dependencies: 
  flutter_test: 
    sdk: flutter
flutter: 
  uses-material-design: true
  assets: 
    - assets/
    - assets/images/
  fonts: 
    - family: Roboto
      fonts: 
        - asset: assets/fonts/RobotoRomanExtraBold.ttf
          weight: 800
        - asset: assets/fonts/RobotoRomanLight.ttf
          weight: 300
        - asset: assets/fonts/RobotoRomanRegular.ttf
          weight: 400
    - family: fontFrames
      fonts: 
        - asset: assets/fonts/font frames.ttf
          weight: 500
    - family: chatKit
      fonts: 
        - asset: assets/fonts/Chatkit.ttf
          weight: 300
    - family: cityWeek
      fonts: 
        - asset: assets/fonts/Cityweek.ttf
          weight: 400
    - family: robotoBold
      fonts: 
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 400
    - family: cityLines
      fonts: 
        - asset: assets/fonts/Citylines.ttf
          weight: 400
    - family: monday
      fonts: 
        - asset: assets/fonts/Monday Coffee.ttf
          weight: 400
    - family: framesG
      fonts: 
        - asset: assets/fonts/GlukFramesM7C-Azure.ttf
          weight: 400
